// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftwareDevelopment2.Data;

#nullable disable

namespace SoftwareDevelopment2.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230613202355_BookProperty")]
    partial class BookProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SoftwareDevelopment2.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfRelease")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 1",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 1",
                            YearOfRelease = 1998
                        },
                        new
                        {
                            Id = 2,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 2",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 2",
                            YearOfRelease = 1999
                        },
                        new
                        {
                            Id = 3,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 3",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 3",
                            YearOfRelease = 2000
                        },
                        new
                        {
                            Id = 4,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 4",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 4",
                            YearOfRelease = 2001
                        },
                        new
                        {
                            Id = 5,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 5",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 5",
                            YearOfRelease = 2002
                        },
                        new
                        {
                            Id = 6,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 6",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 6",
                            YearOfRelease = 2003
                        },
                        new
                        {
                            Id = 7,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 7",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 7",
                            YearOfRelease = 2004
                        },
                        new
                        {
                            Id = 8,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 8",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 8",
                            YearOfRelease = 2005
                        },
                        new
                        {
                            Id = 9,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 9",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 9",
                            YearOfRelease = 2006
                        },
                        new
                        {
                            Id = 10,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 10",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 10",
                            YearOfRelease = 2007
                        },
                        new
                        {
                            Id = 11,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 11",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 11",
                            YearOfRelease = 2008
                        },
                        new
                        {
                            Id = 12,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 12",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 12",
                            YearOfRelease = 2009
                        },
                        new
                        {
                            Id = 13,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 13",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 13",
                            YearOfRelease = 2010
                        },
                        new
                        {
                            Id = 14,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 14",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 14",
                            YearOfRelease = 2011
                        },
                        new
                        {
                            Id = 15,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 15",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 15",
                            YearOfRelease = 2012
                        },
                        new
                        {
                            Id = 16,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 16",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 16",
                            YearOfRelease = 2013
                        },
                        new
                        {
                            Id = 17,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 17",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 17",
                            YearOfRelease = 2014
                        },
                        new
                        {
                            Id = 18,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 18",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 18",
                            YearOfRelease = 2015
                        },
                        new
                        {
                            Id = 19,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 19",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 19",
                            YearOfRelease = 2016
                        },
                        new
                        {
                            Id = 20,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 20",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 20",
                            YearOfRelease = 2017
                        },
                        new
                        {
                            Id = 21,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 21",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 21",
                            YearOfRelease = 2018
                        },
                        new
                        {
                            Id = 22,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 22",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 22",
                            YearOfRelease = 2019
                        },
                        new
                        {
                            Id = 23,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 23",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 23",
                            YearOfRelease = 2020
                        },
                        new
                        {
                            Id = 24,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 24",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 24",
                            YearOfRelease = 2021
                        },
                        new
                        {
                            Id = 25,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 25",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 25",
                            YearOfRelease = 2022
                        },
                        new
                        {
                            Id = 26,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 26",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 26",
                            YearOfRelease = 2023
                        },
                        new
                        {
                            Id = 27,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 27",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 27",
                            YearOfRelease = 2024
                        },
                        new
                        {
                            Id = 28,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 28",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 28",
                            YearOfRelease = 2025
                        },
                        new
                        {
                            Id = 29,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 29",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 29",
                            YearOfRelease = 2026
                        },
                        new
                        {
                            Id = 30,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 30",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 30",
                            YearOfRelease = 2027
                        },
                        new
                        {
                            Id = 31,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 31",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 31",
                            YearOfRelease = 2028
                        },
                        new
                        {
                            Id = 32,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 32",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 32",
                            YearOfRelease = 2029
                        },
                        new
                        {
                            Id = 33,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 33",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 33",
                            YearOfRelease = 2030
                        },
                        new
                        {
                            Id = 34,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 34",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 34",
                            YearOfRelease = 2031
                        },
                        new
                        {
                            Id = 35,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 35",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 35",
                            YearOfRelease = 2032
                        },
                        new
                        {
                            Id = 36,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 36",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 36",
                            YearOfRelease = 2033
                        },
                        new
                        {
                            Id = 37,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 37",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 37",
                            YearOfRelease = 2034
                        },
                        new
                        {
                            Id = 38,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 38",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 38",
                            YearOfRelease = 2035
                        },
                        new
                        {
                            Id = 39,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 39",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 39",
                            YearOfRelease = 2036
                        },
                        new
                        {
                            Id = 40,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 40",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 40",
                            YearOfRelease = 2037
                        },
                        new
                        {
                            Id = 41,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 41",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 41",
                            YearOfRelease = 2038
                        },
                        new
                        {
                            Id = 42,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 42",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 42",
                            YearOfRelease = 2039
                        },
                        new
                        {
                            Id = 43,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 43",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 43",
                            YearOfRelease = 2040
                        },
                        new
                        {
                            Id = 44,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 44",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 44",
                            YearOfRelease = 2041
                        },
                        new
                        {
                            Id = 45,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 45",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 45",
                            YearOfRelease = 2042
                        },
                        new
                        {
                            Id = 46,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 46",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 46",
                            YearOfRelease = 2043
                        },
                        new
                        {
                            Id = 47,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 47",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 47",
                            YearOfRelease = 2044
                        },
                        new
                        {
                            Id = 48,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 48",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 48",
                            YearOfRelease = 2045
                        },
                        new
                        {
                            Id = 49,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 49",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 49",
                            YearOfRelease = 2046
                        },
                        new
                        {
                            Id = 50,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 50",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 50",
                            YearOfRelease = 2047
                        },
                        new
                        {
                            Id = 51,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 51",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 51",
                            YearOfRelease = 2048
                        },
                        new
                        {
                            Id = 52,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 52",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 52",
                            YearOfRelease = 2049
                        },
                        new
                        {
                            Id = 53,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 53",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 53",
                            YearOfRelease = 2050
                        },
                        new
                        {
                            Id = 54,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 54",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 54",
                            YearOfRelease = 2051
                        },
                        new
                        {
                            Id = 55,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 55",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 55",
                            YearOfRelease = 2052
                        },
                        new
                        {
                            Id = 56,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 56",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 56",
                            YearOfRelease = 2053
                        },
                        new
                        {
                            Id = 57,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 57",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 57",
                            YearOfRelease = 2054
                        },
                        new
                        {
                            Id = 58,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 58",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 58",
                            YearOfRelease = 2055
                        },
                        new
                        {
                            Id = 59,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 59",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 59",
                            YearOfRelease = 2056
                        },
                        new
                        {
                            Id = 60,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 60",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 60",
                            YearOfRelease = 2057
                        },
                        new
                        {
                            Id = 61,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 61",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 61",
                            YearOfRelease = 2058
                        },
                        new
                        {
                            Id = 62,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 62",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 62",
                            YearOfRelease = 2059
                        },
                        new
                        {
                            Id = 63,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 63",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 63",
                            YearOfRelease = 2060
                        },
                        new
                        {
                            Id = 64,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 64",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 64",
                            YearOfRelease = 2061
                        },
                        new
                        {
                            Id = 65,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 65",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 65",
                            YearOfRelease = 2062
                        },
                        new
                        {
                            Id = 66,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 66",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 66",
                            YearOfRelease = 2063
                        },
                        new
                        {
                            Id = 67,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 67",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 67",
                            YearOfRelease = 2064
                        },
                        new
                        {
                            Id = 68,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 68",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 68",
                            YearOfRelease = 2065
                        },
                        new
                        {
                            Id = 69,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 69",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 69",
                            YearOfRelease = 2066
                        },
                        new
                        {
                            Id = 70,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 70",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 70",
                            YearOfRelease = 2067
                        },
                        new
                        {
                            Id = 71,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 71",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 71",
                            YearOfRelease = 2068
                        },
                        new
                        {
                            Id = 72,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 72",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 72",
                            YearOfRelease = 2069
                        },
                        new
                        {
                            Id = 73,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 73",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 73",
                            YearOfRelease = 2070
                        },
                        new
                        {
                            Id = 74,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 74",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 74",
                            YearOfRelease = 2071
                        },
                        new
                        {
                            Id = 75,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 75",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 75",
                            YearOfRelease = 2072
                        },
                        new
                        {
                            Id = 76,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 76",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 76",
                            YearOfRelease = 2073
                        },
                        new
                        {
                            Id = 77,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 77",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 77",
                            YearOfRelease = 2074
                        },
                        new
                        {
                            Id = 78,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 78",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 78",
                            YearOfRelease = 2075
                        },
                        new
                        {
                            Id = 79,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 79",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 79",
                            YearOfRelease = 2076
                        },
                        new
                        {
                            Id = 80,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 80",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 80",
                            YearOfRelease = 2077
                        },
                        new
                        {
                            Id = 81,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 81",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 81",
                            YearOfRelease = 2078
                        },
                        new
                        {
                            Id = 82,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 82",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 82",
                            YearOfRelease = 2079
                        },
                        new
                        {
                            Id = 83,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 83",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 83",
                            YearOfRelease = 2080
                        },
                        new
                        {
                            Id = 84,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 84",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 84",
                            YearOfRelease = 2081
                        },
                        new
                        {
                            Id = 85,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 85",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 85",
                            YearOfRelease = 2082
                        },
                        new
                        {
                            Id = 86,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 86",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 86",
                            YearOfRelease = 2083
                        },
                        new
                        {
                            Id = 87,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 87",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 87",
                            YearOfRelease = 2084
                        },
                        new
                        {
                            Id = 88,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 88",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 88",
                            YearOfRelease = 2085
                        },
                        new
                        {
                            Id = 89,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 89",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 89",
                            YearOfRelease = 2086
                        },
                        new
                        {
                            Id = 90,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 90",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 90",
                            YearOfRelease = 2087
                        },
                        new
                        {
                            Id = 91,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 91",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 91",
                            YearOfRelease = 2088
                        },
                        new
                        {
                            Id = 92,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 92",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 92",
                            YearOfRelease = 2089
                        },
                        new
                        {
                            Id = 93,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 93",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 93",
                            YearOfRelease = 2090
                        },
                        new
                        {
                            Id = 94,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 94",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 94",
                            YearOfRelease = 2091
                        },
                        new
                        {
                            Id = 95,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 95",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 95",
                            YearOfRelease = 2092
                        },
                        new
                        {
                            Id = 96,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 96",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 96",
                            YearOfRelease = 2093
                        },
                        new
                        {
                            Id = 97,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 97",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 97",
                            YearOfRelease = 2094
                        },
                        new
                        {
                            Id = 98,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 98",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 98",
                            YearOfRelease = 2095
                        },
                        new
                        {
                            Id = 99,
                            Author = "J.K. Rowling",
                            Location = "Verdieping 99",
                            Price = 8.9900000000000002,
                            Title = "Harry Potter: 99",
                            YearOfRelease = 2096
                        });
                });

            modelBuilder.Entity("SoftwareDevelopment2.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("SoftwareDevelopment2.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("SoftwareDevelopment2.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeGroup")
                        .HasColumnType("int");

                    b.Property<int>("ExtendsInARow")
                        .HasColumnType("int");

                    b.Property<float>("FinePerItemPerDay")
                        .HasColumnType("real");

                    b.Property<int>("ItemsAtSameTime")
                        .HasColumnType("int");

                    b.Property<int>("ItemsPerYear")
                        .HasColumnType("int");

                    b.Property<int>("LoanPeriodInDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ReservationCost")
                        .HasColumnType("real");

                    b.Property<float>("SubscriptionCostPerMonth")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
