
name: Testing Docker Image with Goss

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    branches: [main]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install GOSS
        run: |
          curl -fsSL https://goss.rocks/install | sh
      
      - name: Pull Docker image and run test
        run: dgoss run nalanyw/my-image:main 

      - name: Run health check
        run: |
          goss serve &
          curl localhost:8080/healthz

  
